name: Release

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    # types: 
    #   - completed

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          cache: true
      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser | sh
          echo $PATH
          export PATH=$PATH:/go/bin
      - name: Run GoReleaser
        run: |
          goreleaser release --config .github/.goreleaser.yaml --release-notes CHANGELOG.md --allow-initial-development-versions --release-notes-mode prepend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
