name: Release

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          cache: true
      - name: Create Release
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          changelog-file: CHANGELOG.md
          allow-initial-development-versions: true
          prepend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
